2021-03-27 16:27:33,206 - 
Downloading Utility Log. 
Log started.

Move log to Impt Logs if required as only the 10 most recent logs are kept.

2021-03-27 16:27:34,306 - Command: dl -youtube https://www.youtube.com/channel/UCPxHg4192hLDpTI2w7F9rPg
2021-03-27 16:27:34,307 - youtube link
2021-03-27 16:27:34,945 - file_cache is only supported with oauth2client<4.0.0
2021-03-27 16:27:35,123 - local variable 'list_of_ids' referenced before assignment
Traceback (most recent call last):
  File "c:/Utilities/Scripts/url-dl-v2/main.py", line 240, in <module>
    parse_input()
  File "c:/Utilities/Scripts/url-dl-v2/main.py", line 123, in parse_input
    Downloader = youtube_extractor(Downloader) #Downloader_2 because Downloader causes errors.
  File "c:\Utilities\Scripts\url-dl-v2\extractors\youtube.py", line 214, in youtube_extractor
    if len(list_of_ids) != video_count:
UnboundLocalError: local variable 'list_of_ids' referenced before assignment
2021-03-27 16:27:35,124 - 
Log Ended.
Total time: 0 hrs 0 min 1.92 sec

